# 1. Kết nối 
spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=BankingDB;integratedSecurity=true;encrypt=true;trustServerCertificate=true;
# Xóa hoặc comment lại hai dòng username và password đi
# spring.datasource.username=sa
# spring.datasource.password=Password_Cua_Ban_123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 2. Quản lý cấu trúc bảng (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# 3. Chạy file schema.sql và data.sql
spring.sql.init.mode=never